% MATLAB Code
% Generated by MATLAB 9.3 and Phased Array System Toolbox 3.5
% Generated on 30-Nov-2017 11:02:43

% Mode Of Operation: Active

% All quantities are in standard units

NoiseLevel = 73;									% Noise Level (dB//1uPa)
DirectivityIndex = 20;								% Directivity Index (dB)
TargetStrength = 25;								% Target Strength (dB)
Frequency = 2000;									% Frequency (Hz)
Depth = 10000;										% Depth(m)
SourceLevel = 220;									% Source Level(dB//1uPa)
SNR = shnidman(0.81029,0.001,1,0);					% SNR (dB)

TransmissionLoss = sonareqtl(SourceLevel, SNR, NoiseLevel, ...
    DirectivityIndex,TargetStrength );
TargetRange = tl2range(TransmissionLoss,Frequency,Depth);
